### ISSUE TITLE
Table cell images sometimes overflow

### ISSUE THREAD

**Issue by klazuka** [klazuka/TTRemoteExamples#1]

**Comment by klazuka** [comment]
This can be mitigated by disabling the image cache. It appears that TTTableImageItemCell takes a different code path if the image is found in the cache. I still need to look into this more.

My best guess is that when the image is not in the cache, it does the layout and returns the rowHeight based on the default image's dimensions. Later, after the URL request finishes and the image is in memory, either it is not triggering a new layout, or the tableView does not ask it for its rowHeight again (probably the latter).

**Comment by ZoBoRf** [comment]
You can try to set an ImageStyle with a defined size like this in SearchResultsTableDataSource.m:

<pre>
- (void)tableViewDidLoadModel:(UITableView *)tableView
{
    [super tableViewDidLoadModel:tableView];
    
    TTLOG(@"Removing all objects in the table view.");
    [self.items removeAllObjects];
#if 0     
    // Construct an object that is suitable for the table view system
    // from each SearchResult domain object that we retrieve from the TTModel.
    for (SearchResult *result in [(id<SearchResultsModel>)self.model results])
        [self.items addObject:[TTTableImageItem itemWithText:result.title
                                                    imageURL:result.thumbnailURL
                                                defaultImage:[UIImage imageNamed:@"photo_placeholder.png"]
                                                         URL:nil]];
#else
      for (SearchResult *result in [(id<SearchResultsModel>)self.model results])
      {
        TTTableImageItem* tii = [TTTableImageItem itemWithText:result.title
                                                      imageURL:result.thumbnailURL
                                                  defaultImage:[UIImage imageNamed:@"photo_placeholder.png"]
                                                           URL:nil];
        CGSize size;
        size.width = 75.f;
        size.height = 75.f;
        
        tii.imageStyle = [TTImageStyle styleWithImage:nil 
                                         defaultImage:[UIImage imageNamed:@"photo_placeholder.png"] 
                                          contentMode:UIViewContentModeScaleAspectFill                        
//                                        contentMode:UIViewContentModeScaleAspectFit                            
                                                 size:size next:nil];
        [self.items addObject:tii];
      }
#endif
    TTLOG(@"Added %lu search result objects", (unsigned long)[self.items count]);
}
</pre>

**Comment by klazuka** [comment]
Thanks RoBak42. I applied your patch and it did indeed fix the problem. This issue is resolved as of SHA: 4db7e170202124a1cf98209253199319ab6aca40
