### ISSUE TITLE
The spinner in the TTPhotoView doesn't hide after image loads

### ISSUE THREAD

**Issue by samiq** [klazuka/TTRemoteExamples#10]
when the user navigates to an image from the result set the spinners start spinning while the image loads yet it never goes away after the image has loaded. I found this is a problem related that to the photo item not having a photosource and hence calling the isLoading on it always results to false.

For my project I just removed the checking for this isLoading although I know this is not the best way to get it done but I am on a time crunch so for now it works. 

hope you can take a look.

cheers,

G.

**Comment by klazuka** [comment]
I probably won't fix this--I haven't used Three20 for nearly a year, so TTRemoteExamples is, effectively, unmaintained.
