### ISSUE TITLE
Missing SDK in target TTRemoteExamples: iphoneos3.0

### ISSUE THREAD

**Issue by linearshift** [klazuka/TTRemoteExamples#11]
Hi,

I just followed the examples to run the sample app but when I run I get the a build failed error with a message: 

Missing SDK in target TTRemoteExamples: iphoneos3.0

I'm using xCode 4 with the latest SDK, and pointers as to how I might get around this would be much appreciated as I suspect it is more likely something to do with my configuration than your code

Thanks in advance,

Tim

**Comment by linearshift** [comment]
of course the answer is always in the question - so I changed the Base SDK

**Comment by klazuka** [comment]
Sorry it took so long to reply--I've been working 12 hour days and I
just let my inbox overflow.

You need to change the "Base SDK" in the Project Settings. I still use
Xcode 3, so unfortunately I don't know how to change it in Xcode 4.

-keith

On Tue, May 24, 2011 at 10:42 AM, linearshift
reply@reply.github.com
wrote:
