### ISSUE TITLE
imageForError:

### ISSUE THREAD

**Issue by revetkn** [klazuka/TTRemoteExamples#4]
Hi Keith -

Just wanted to say thanks for all your work on this, the code you've provided is very helpful and much appreciated.  Wanted to mention a really minor issue, though - SearchTableViewController's imageForError: will never be invoked, since it's a selector for TTTableViewDataSource...just move imageForError: over to SearchResultsTableDataSource to fix.

**Comment by klazuka** [comment]
Thanks for noticing this. Fixed in the newest version (but not pushed up to GitHub yet).
